Sprint 6 solution
marzhanabdrahmanova/java-kanban pull request #2
Opened 2024-08-28 14:35 UTC by marzhanabdrahmanova

2024-08-28 14:40 UTC, marzhanabdrahmanova commented
tests have been passed

2024-08-28 15:36 UTC, afomkina requested changes

2024-08-28 15:36 UTC, afomkina commented on src/manager/InMemoryHistoryManager.java
> +            tail = newNode;
Нужно вынести общую строку `tail = newNode;` за пределы условного оператора для упрощения кода и повышения его читабельности.

2024-08-28 15:36 UTC, afomkina commented on src/manager/Node.java
> +    Task task;
У полей класса должен быть модификатор доступа.
Также лучше добавить геттеры и сеттеры для взаимодействиями с полями

2024-08-29 13:17 UTC, afomkina approved these changes

2024-10-17 04:42 UTC, merged